language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text

after_script:
  - "if [ $(phpenv version-name) = '7.0' ]; then php ./vendor/bin/phpcov merge --clover ./build/logs/clover.xml ./build/coverage/; fi"
  - "if [ $(phpenv version-name) = '7.0' ]; then php ./vendor/bin/coveralls -v --exclude-no-stmt; fi"

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
