language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text

after_script:
  - php ./vendor/bin/phpcov merge --clover ./build/logs/clover.xml ./build/coverage/
  - php ./vendor/bin/coveralls -v --exclude-no-stmt

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
