language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug  && make && make install && echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi
  - ./vendor/bin/phpunit --coverage-text

after_script:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then php ./vendor/bin/phpcov merge --clover ./build/logs/clover.xml ./build/coverage/; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then php ./vendor/bin/coveralls -v --exclude-no-stmt; fi

notifications:
  email: false

matrix:
  fast_finish: true
