language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit --coverage-text

after_script:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then php ./vendor/bin/phpcov merge --clover ./build/logs/clover.xml ./build/coverage/; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then php ./vendor/bin/coveralls -v --exclude-no-stmt; fi

notifications:
  email: false

matrix:
  fast_finish: true
