language: php

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.3
        env:
          - DEPS=lowest
    - php: 7.3
        env:
          - DEPS=latest
    - php: 7.4
        env:
          - DEPS=lowest
    - php: 7.4
        env:
          - DEPS=latest

before_script:
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer install --prefer-source --no-interaction ; fi

script:
  - if [[ $DEPS == 'latest' ]]; then composer cs-check ; fi
  - mkdir -p ./build/logs
  - ./vendor/bin/phpunit --coverage-text

after_script:
  - if [[ $DEPS == 'latest' ]]; then php ./vendor/bin/php-coveralls -v --exclude-no-stmt; fi

notifications:
  email: false
